apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: giropops-pipeline
spec:
  workspaces:
    - name: giropops
      description: The git repo of Otavio typescript example
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRevision
      description: Git revision to check out
      default: master
    - name: pathToContext
